server:
  port: 8081
spring:
  application:
    name: hocade-api-gateway

  cloud:
    gateway:
      routes:
        - id: api-route
          uri: http://localhost:9091
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - OAuthGatewayFilter=
          order: 1
        - id: websocket-route
          uri: ws://localhost:9092
          predicates:
            - Path=/ws/**
          order: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: {YOUR_JWK_SET_URI} # JWT 토큰을 검증하기 위한 JWK Set URI
          issuer-uri: {YOUR_ISSUER_URI}   # JWT 토큰 발급자(issuer) URI

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE